/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./*.HTML", "./*.html", "./**/*.HTML", "./**/*.html"],
    theme: {
        extend: {
            colors: {
                "primary-dim": "#bb00fc",
                "on-primary-container": "#3d0055",
                "on-surface-variant": "#aba7ca",
                "surface-dim": "#0c0a25",
                "error": "#ff6e84",
                "surface-container-lowest": "#000000",
                "outline": "#757292",
                "primary-container": "#d878ff",
                "primary": "#df8eff",
                "tertiary-fixed-dim": "#ff769e",
                "on-error": "#490013",
                "surface-container-low": "#110f2d",
                "secondary-fixed-dim": "#00d7f0",
                "inverse-primary": "#9a00d0",
                "on-secondary-fixed": "#003a42",
                "secondary-container": "#006875",
                "on-error-container": "#ffb2b9",
                "on-primary": "#4f006d",
                "surface-container": "#181536",
                "surface-bright": "#2a2751",
                "tertiary": "#ff6b98",
                "inverse-surface": "#fcf8ff",
                "error-dim": "#d73357",
                "on-tertiary-container": "#000000",
                "error-container": "#a70138",
                "tertiary-fixed": "#ff8eac",
                "surface-tint": "#df8eff",
                "on-primary-fixed": "#000000",
                "outline-variant": "#474563",
                "on-secondary-container": "#e8fbff",
                "on-secondary": "#004d57",
                "on-primary-fixed-variant": "#4b0068",
                "secondary-dim": "#00d4ec",
                "secondary": "#00e3fd",
                "primary-fixed": "#d878ff",
                "secondary-fixed": "#26e6ff",
                "on-tertiary-fixed-variant": "#760035",
                "tertiary-container": "#fc0078",
                "primary-fixed-dim": "#d061ff",
                "on-tertiary-fixed": "#380015",
                "on-tertiary": "#47001d",
                "tertiary-dim": "#e4006c",
                "surface": "#0c0a25",
                "on-surface": "#e6e2ff",
                "surface-container-highest": "#232148",
                "inverse-on-surface": "#545270",
                "surface-variant": "#232148",
                "background": "#0c0a25",
                "surface-container-high": "#1d1b3f",
                "on-background": "#e6e2ff",
                "on-secondary-fixed-variant": "#005964"
            },
            fontFamily: {
                "headline": ["Lexend"],
                "body": ["Plus Jakarta Sans"],
                "label": ["Lexend"]
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries'),
    ],
}
